# -*- coding: utf-8 -*-
"""position_wise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14elkzB7PL66A-BTKz8F8s5xxSTwH-LGg
"""

import torch
import torch.nn.functional as F
import torch.nn as nn

class PositionWiseFeedForward(nn.module):
  def __init__(self):
    super().__init__()
    self.conv_layer1 = nn.Conv1d()
    self.conv_layer2 = nn.Conv1d()
    self.activation = F.relu

  def forward(self,inputs):

    output = self.conv_layer1(inputs)
    output = self.activation(output)
    output = self.conv_layer2(output)

    return {"pos_wise":output}