# -*- coding: utf-8 -*-
"""transformer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14tLYLjETlHd4WJFJZ9Avn3x90A367fhY
"""

import torch
import torch.nn as nn

class Transformer(nn.module):
  def __init__(self):
    super().__init__()

    self.encoder = encoder()
    self.decoder = decoder()

  def forward(self,encoder_input, decoder_input):
    
    '''
    마스크를 미리 생성한 뒤,
    넣어줄지, 각 encoder, decoder에서 생성할지 고민
    '''
    en_output = self.encoder(encoder_input)
    output = self.decoder(decoder_input, en_output)

    return output

  ## 보류
  def get_att_mask(size):
    return mask